# name: monitoring_kolam_ikan
# description: "A new Flutter project."
# publish_to: 'none' 
# version: 1.0.0+1

# environment:
#   sdk: '>=3.4.3 <4.0.0'
# dependencies:
#   fl_chart: ^0.69.0
#   flutter:
#     sdk: flutter
#   mqtt_client: ^10.0.0
#   font_awesome_flutter: ^10.5.0
#   line_icons: ^2.0.1
#   wifi_iot: ^0.3.19
#   fluttertoast: ^8.2.4
#   shared_preferences: ^2.2.2
#   animations: ^2.0.7  
#   cupertino_icons: ^1.0.6
#   firebase_core: ^3.6.0  # Tambahkan Firebase Core
#   cloud_firestore: ^5.4.4 # Tambahkan Cloud Firestore

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^3.0.0
#   flutter_launcher_icons: ^0.13.1
# flutter:
#   uses-material-design: true
#   assets:
#     - assets/ludang.jpg
#     - assets/ibnu.jpg
#     - assets/fadrian.jpg


# flutter_icons:
#   android: true
#   ios: false
#   image_path: "assets/icon/app_icon.png"
# name: monitoring_kolam_ikan
# description: "A new Flutter project."
# publish_to: 'none'
# version: 1.0.0+1

# environment:
#   sdk: '>=3.4.3 <4.0.0'

# dependencies:
#   flutter:
#     sdk: flutter
#   mqtt_client: ^10.0.0
#   font_awesome_flutter: ^10.5.0
#   line_icons: ^2.0.1
#   wifi_iot: ^0.3.19
#   fluttertoast: ^8.2.4
#   shared_preferences: ^2.2.2
#   animations: ^2.0.7
#   cupertino_icons: ^1.0.6
#   firebase_core: ^3.6.0  # Tambahkan untuk inisialisasi Firebase
#   cloud_firestore: ^5.4.4 # Tambahkan untuk Firestore
#   fl_chart: ^0.69.0      # Tambahkan untuk grafik

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^3.0.0
#   flutter_launcher_icons: ^0.13.1

# flutter:
#   uses-material-design: true
#   assets:
#     - assets/ludang.jpg
#     - assets/ibnu.jpg
#     - assets/fadrian.jpg

# flutter_icons:
#   android: true
#   ios: false
#   image_path: "assets/icon/app_icon.png"

name: monitoring_kolam_ikan
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^10.0.0
  font_awesome_flutter: ^10.5.0
  line_icons: ^2.0.1
  wifi_iot: ^0.3.19
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  animations: ^2.0.7
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/ludang.jpg
    - assets/ibnu.jpg
    - assets/fadrian.jpg

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"