// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASB15Aegg57nnhZTZR9Pu6TKlKZRmaCtQ',
    appId: '1:845647627682:web:8506fb4d2f9ffa5f7edefb',
    messagingSenderId: '845647627682',
    projectId: 'iotkolam-c5bf2',
    authDomain: 'iotkolam-c5bf2.firebaseapp.com',
    storageBucket: 'iotkolam-c5bf2.firebasestorage.app',
    measurementId: 'G-V6S8VK7W2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnpRstmSMC6PWTwlAQmxU6PueQAlRiYpk',
    appId: '1:845647627682:android:7919d7d20fc449287edefb',
    messagingSenderId: '845647627682',
    projectId: 'iotkolam-c5bf2',
    storageBucket: 'iotkolam-c5bf2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASB15Aegg57nnhZTZR9Pu6TKlKZRmaCtQ',
    appId: '1:845647627682:web:3921dad6e93d38847edefb',
    messagingSenderId: '845647627682',
    projectId: 'iotkolam-c5bf2',
    authDomain: 'iotkolam-c5bf2.firebaseapp.com',
    storageBucket: 'iotkolam-c5bf2.firebasestorage.app',
    measurementId: 'G-1136038L0L',
  );
}
